version: "2"
containers:
- name: vault-cli
  image: vault:1.2.3
  shell: /bin/sh
  ports:
  - 8200
  environment:
    VAULT_ADDR: http://localhost:8200
    VAULT_DEV_ROOT_TOKEN_ID: root
    VAULT_TOKEN: root
