version: "2"
containers:
- name: vault-cli
  image: gcr.io/instruqt-hashicorp/vault:1.2.3
  shell: /bin/sh
  ports:
  - 8200
  environment:
    SKIP_SETCAP: "false"
    VAULT_ADDR: http://localhost:8200
    VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "log_level":
      "Trace", "disable_mlock": "true", "ui": "true", "listener": {"tcp": {"address":"0.0.0.0:8200",
      "tls_disable":"true"}}}'
